image:
  repository: tccr.io/truecharts/freshrss
  pullPolicy: IfNotPresent
  tag: v1.20.0@sha256:8f4ac3ac0a2e2c733a8755dc16ba4c5b22c8d8e90d85adbd535c2761aaf272e3

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
