env:
  VNC_PW: unraid
  VNC_RESOLUTION: 1360x768
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/opengl-desktop-g3
  tag: latest@sha256:beb88da26682936cdfae4fa31ea9f7c3e91ee094e5b1c3cfb2aba7e8e5e20972
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6901
        protocol: HTTP
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: TCP
        targetPort: 5901

portal:
  enabled: true
