env:
  SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/sonarqube
  tag: latest@sha256:a3150ef1316ee1afc954c5f9ad3003f19e45e00c26bf0c5a7ac02f79fb6e57b4
persistence:
  data:
    enabled: true
    mountPath: /opt/sonarqube/data
  extensions:
    enabled: true
    mountPath: /opt/sonarqube/extensions
  logs:
    enabled: true
    mountPath: /opt/sonarqube/logs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 9000
        protocol: TCP
        targetPort: 9000

portal:
  enabled: true
