env:
  PORT: "3000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/vertex
  tag: vstable@sha256:22a07e8d716be67f454c5b18896aaea45c6d56780b31743589a06d327d474b4f
persistence:
  config:
    enabled: true
    mountPath: /vertex
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3000
        protocol: TCP
        targetPort: 3000

portal:
  enabled: true
