image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/plextraktsync
  tag: latest@sha256:a4da831ae057e44b3a639179cc1dfe2260fa898ae46d2ac08744329a989493af

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

tty: true
stdin: true

plexTraktSync:
  task: ""
  schedule: "0 */6 * * *"

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  config:
    enabled: true
    mountPath: /app/config

portal:
  enabled: false

cronjob:
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
