image:
  repository: tccr.io/truecharts/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:410eb9ce36273c43b85161df77f2545b618c146471366f91bdf3782e4f8f5e0a

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
