env:
  KEYBOARD: ""
  SUBFOLDER: ""
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/webtop
  tag: latest@sha256:a990df4fac8b29dcc3b371c6081ad29f73b1c2fc6805ad12d5748541fe6c7a96
persistence:
  config:
    enabled: true
    mountPath: /config

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3000
        protocol: TCP
        targetPort: 3000

portal:
  enabled: true
