image:
  repository: tccr.io/truecharts/openspeedtest
  pullPolicy: IfNotPresent
  tag: latest@sha256:4c4c9d6d6ce60b8040dca2daa5769b91ca02f5fbc6734b6fd8e6b3c773d035e8

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10256

portal:
  enabled: true
