image:
  repository: tccr.io/truecharts/stash
  tag: 0.17.1@sha256:a1f967404b546f935e705cfc74edeb05073f5dadd3026dd7b2de0223a361e5ab
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  STASH_PORT: "{{ .Values.service.main.ports.main.port }}"
  # STASH_STASH:
  # STASH_GENERATED:
  # STASH_METADATA:
  # STASH_CACHE:

service:
  main:
    ports:
      main:
        port: 9999

persistence:
  config:
    enabled: true
    mountPath: "/root/.stash"

portal:
  enabled: true
