image:
  repository: tccr.io/truecharts/kavita
  pullPolicy: IfNotPresent
  tag: 0.6.0@sha256:d4f39bdc036ddfbc1b210d8638fc7db6ad5fde3d4f57e418d6f5e2ac017a4872

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189

persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"

portal:
  enabled: true
