image:
  repository: tccr.io/truecharts/inventree
  tag: 0.8.3@sha256:613beaed5d0a1940b6e5027b6da6c698dfd2d01848b8ac8d27237560ec34006f
  pullPolicy: IfNotPresent

nginxImage:
  repository: tccr.io/truecharts/nginx
  tag: 1.23.2@sha256:2731d5e0ea922af41880719dc4c251abf5b081ed480c8b0a0f323174dcb06ff4
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
# https://github.com/inventree/InvenTree/pull/3096
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-inventree-secret'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-inventree-config'

inventree:
  credentials:
    admin_mail: "test@example.com"
    admin_user: "testuser"
    admin_password: "secret"
  general:
    debug: false
    log_level: "INFO"
    plugins_enabled: false
    login_confirm_days: 3
    login_attempts: 5
  mail:
    backend: "django.core.mail.backends.smtp.EmailBackend"
    host: ""
    port: 587
    username: ""
    password: ""
    tls: false
    ssl: false
    sender: ""

service:
  main:
    ports:
      main:
        port: 10231

persistence:
  data:
    enabled: true
    mountPath: "/home/inventree/data"
  inventree-nginx:
    enabled: true
    noMount: true
    type: custom
    mountPath: "/etc/nginx/conf.d"
    volumeSpec:
      configMap:
        name: '{{ include "tc.common.names.fullname" . }}-inventree-config-nginx'
        items:
          - key: nginx.conf
            path: default.conf

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: inventree
  postgresqlDatabase: inventree

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: default

portal:
  enabled: true
