image:
  repository: tccr.io/truecharts/drawio
  tag: 20.4.2@sha256:1a2a0ceddc2b3feaf917d9cd02af498ac4dd784500f3901cf9f276ea2a7a92f9
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080

portal:
  enabled: true
