env:
  HOSTS: "['qemu:///system']"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/virt-manager
  tag: latest@sha256:914b2d70f3a139e595f6d3e955a58eed048dec158b268bcbe061b4486cf9538a
persistence:
  devkvm:
    enabled: true
    mountPath: /dev/kvm
  images:
    enabled: true
    mountPath: /var/lib/libvirt/images
  libvirt-sock:
    enabled: true
    mountPath: /var/run/libvirt/libvirt-sock
  rootfolder:
    enabled: true
    mountPath: /root
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8185
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
