image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ring-mqtt
  tag: 5.0.5@sha256:f9c196a89c271ad0bc6e7d9604b2519af28e4f8915ea376660851d3b10f1e2ba

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  RINGTOKEN: ""
  MQTTUSER: ""
  MQTTPASSWORD: ""

env:
  BEAMDURATION: "0"
  DISARMCODE: ""
  ENABLECAMERAS: "false"
  ENABLEMODES: "false"
  ENABLEPANIC: "false"
  MQTTHOST: ""
  MQTTPORT: "1883"
  RINGLOCATIONIDS: ""
  SNAPSHOTMODE: disabled

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 55123
        port: 55123
  rtsp:
    enabled: true
    ports:
      rtsp:
        enabled: true
        protocol: TCP
        targetPort: 8554
        port: 8554

persistence:
  data:
    enabled: true
    mountPath: /data

portal:
  enabled: false
