image:
  repository: tccr.io/truecharts/filezilla
  pullPolicy: IfNotPresent
  tag: v3.55.1@sha256:82d31264e95ec7fe89bb89ce6ca20948430c38156531ef2e90e29db7f42de2b7

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10035
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
