env:
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rdesktop
  tag: latest@sha256:16704dd72cbaca9e7a9d75210dc2d5bcf5b5d9638bb1fabd61f3ec4a44458622
persistence:
  config:
    enabled: true
    mountPath: /config

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3389
        protocol: TCP
        targetPort: 3389

portal:
  enabled: true
