image:
  repository: tccr.io/truecharts/autobrr
  pullPolicy: IfNotPresent
  tag: 1.8.0@sha256:4def72ef9b677e7ffc05a72622ac6d79726229e38e06a1fbb029e10fd9298c5e

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 7474
        targetPort: 7474

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - curl --fail localhost:7474/
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - curl --fail localhost:7474/
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
