env:
  FLOOD_AUTH: ""
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/qflood
  tag: latest@sha256:e7449f7f51b8cf1bb2456085ccf9bf1588ca5b01cf3fb921f98721201464065e
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostportfor808:
    enabled: true
    ports:
      hostportfor808:
        enabled: true
        port: 8080
        protocol: TCP
        targetPort: 8080
  main:
    ports:
      main:
        port: 3000
        protocol: HTTP
        targetPort: 3000

portal:
  enabled: true
