image:
  repository: tccr.io/truecharts/cyberchef
  tag: 9.48.0@sha256:cb8f4179ba4ff3dffadc221315cc609800b17628666aee7d18d9d9653d9a0284
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10219
        targetPort: 8000

portal:
  enabled: true
