image:
  repository: tccr.io/truecharts/cyberchef
  tag: 9.48.0@sha256:4851c9fc1871c762c7205c5e648dca60570d1ff6a4ef6aba6b92651a656d0e26
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10219
        targetPort: 8000

portal:
  enabled: true
