env:
  HOME: /root
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cloudcommander
  tag: latest@sha256:a46ae66c638c2d551431635e969f33b5faadeb961e61bd5f620934a5f8fafa05
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8765
        protocol: TCP
        targetPort: 8000

portal:
  enabled: true
