image:
  repository: tccr.io/truecharts/trilium-notes
  pullPolicy: IfNotPresent
  tag: 0.56.1@sha256:9bf7c097da1d6d98d6b6f834af8bfb44212975bb975f5ea82bc7d11ff9b38d2c

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 1000

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 8080
        port: 10156

persistence:
  config:
    enabled: true
    mountPath: "/home/node"

portal:
  enabled: true
