env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/filestash
  tag: latest@sha256:24e14bc1f13eee5a6470171a93522a309be4eff53bc1a04ecf819d3ab248cafc
persistence:
  appdata:
    enabled: true
    mountPath: /app/data/state/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8334
        protocol: TCP
        targetPort: 8334

portal:
  enabled: true
