env:
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  NEXTAUTH_SECRET: ""
  NEXTAUTH_URL: ""
  REDDIT_REDIRECT: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/troddit
  tag: latest@sha256:7c42ecc9fa576c8d737fdb8eb749fc0a87a3a453e648589748934b459ad8187b
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3000
        protocol: TCP
        targetPort: 3000

portal:
  enabled: true
