image:
  repository: tccr.io/truecharts/digikam
  pullPolicy: IfNotPresent
  tag: v7.8.0@sha256:a63cc42f508bdd8832891e1f6ea76fd993912c7b9027d4569a3621a0f358e690

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10033
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
