image:
  repository: tccr.io/truecharts/beets
  pullPolicy: IfNotPresent
  tag: v1.6.0@sha256:107e4f7b8fbeb62cd72570a342390684d006ca4d834d374b89503b36aec035b3

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8337
        targetPort: 8337

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
