image:
  repository: tccr.io/truecharts/rflood
  pullPolicy: IfNotPresent
  tag: latest@sha256:8338fbc409cfce468b5bc2ccd36fd6a0860f75fe5707762e726d4262586faedb

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  FLOOD_AUTH: false

service:
  main:
    ports:
      main:
        port: 3000
        protocol: HTTP
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
