image:
  repository: tccr.io/truecharts/sickchill
  pullPolicy: IfNotPresent
  tag: 2022.10.13@sha256:d764de7107e3c4d1bbab004fc43d26c3a0ac22468264f1c40f1b9d4bd448e89a

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10067
        targetPort: 8081

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
